# Generated by Django 2.1 on 2018-12-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_career_career_pathways"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="description",
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
