# Generated by Django 2.1 on 2019-03-27 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_info"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="careers",
        ),
        migrations.AddField(
            model_name="class",
            name="careers",
            field=models.ManyToManyField(to="api.Career"),
        ),
    ]
