# Generated by Django 2.1 on 2019-04-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190326_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='file_name',
            field=models.FileField(upload_to=''),
        ),
    ]
