# Generated by Django 2.1 on 2020-01-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auto_20190430_1848"),
    ]

    operations = [
        migrations.AlterField(
            model_name="career",
            name="suggested_classes",
            field=models.ManyToManyField(blank=True, to="api.Class"),
        ),
        migrations.AlterField(
            model_name="class",
            name="careers",
            field=models.ManyToManyField(blank=True, to="api.Career"),
        ),
    ]
