# Generated by Django 2.1 on 2021-02-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200207_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='viewable',
            field=models.BooleanField(default=True),
        ),
    ]
