# Generated by Django 2.1 on 2022-01-10 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_class_viewable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='mods',
            new_name='meets',
        ),
    ]
